# Generated by Django 5.1.7 on 2025-05-19 13:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(verbose_name='Начало')),
                ('data_end', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('is_active', models.BooleanField(default=False, verbose_name='Завершена')),
            ],
            options={
                'verbose_name': 'Активность задачи',
                'verbose_name_plural': 'Активность задач',
            },
        ),
        migrations.CreateModel(
            name='AdditionalCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Дополнительные затраты',
                'verbose_name_plural': 'Дополнительные затраты',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Должность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание должности')),
                ('bet', models.IntegerField(verbose_name='Ставка')),
                ('bet_local', models.IntegerField(verbose_name='Внутренняя ставка')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='DocumentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_load', models.DateField(auto_created=True, verbose_name='Дата загрузки')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование проекта')),
                ('category', models.CharField(choices=[('1', 'Договор'), ('2', 'Смета'), ('3', 'Локальная смета'), ('4', 'Доп. соглашение'), ('5', 'Платежные документы'), ('6', 'Акт о закрытии работ'), ('7', 'Приложение к договору'), ('8', 'Акт')], max_length=2, verbose_name='Категория')),
                ('document', models.FileField(upload_to='project/document/%Y/%m/%d/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документы к проекту',
                'verbose_name_plural': 'Документы к проектам',
            },
        ),
        migrations.CreateModel(
            name='FeedbackCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(auto_created=True, verbose_name='Дата подачи')),
                ('data_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата обратной связи')),
                ('report_stuff', models.CharField(max_length=500, verbose_name='Отчет о задаче')),
                ('comment_director', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий от заказчика')),
                ('is_adopted', models.CharField(choices=[('verification', 'На проверке'), ('adopted', 'Принят'), ('rejected', 'Отклонен')], default='verification', max_length=40, verbose_name='Принято')),
            ],
            options={
                'verbose_name': 'Обратная связь от заказчика',
                'verbose_name_plural': 'Обратные связи от заказчика',
            },
        ),
        migrations.CreateModel(
            name='FileTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project/task/%Y/%m/%d/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл к задаче',
                'verbose_name_plural': 'Файлы к задачам',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата создания')),
                ('data_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('category', models.CharField(max_length=10, verbose_name='Категория')),
                ('color_style', models.CharField(default='#6610f2', max_length=10, verbose_name='Цвет уведомления')),
                ('dsc', models.CharField(max_length=500, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='ReportingChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(auto_created=True, verbose_name='Дата подачи')),
                ('data_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата обратной связи')),
                ('report_executor', models.CharField(max_length=500, verbose_name='Отчет от исполнителя')),
                ('comment_customer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий от заказчика')),
                ('status', models.CharField(choices=[('verification', 'На проверке'), ('adopted', 'Принят'), ('rejected', 'Отклонен')], default='verification', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Отчет о разделе',
                'verbose_name_plural': 'Отчет о разделах',
            },
        ),
        migrations.CreateModel(
            name='ReportingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(auto_created=True, verbose_name='Дата подачи')),
                ('data_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата обратной связи')),
                ('report_stuff', models.CharField(max_length=500, verbose_name='Отчет от сотрудника')),
                ('comment_director', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий от директора')),
                ('is_adopted', models.CharField(choices=[('verification', 'На проверке'), ('adopted', 'Принят'), ('rejected', 'Отклонен')], default='verification', max_length=40, verbose_name='Принято')),
            ],
            options={
                'verbose_name': 'Отчет о задаче',
                'verbose_name_plural': 'Отчет о задачах',
            },
        ),
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_salary', models.DateField(verbose_name='Дата оплаты')),
                ('category', models.CharField(choices=[('1', 'Зарплата'), ('2', 'Оплата заказчика')], max_length=1, verbose_name='Категория')),
                ('payment', models.IntegerField(verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Зарплатный проект',
                'verbose_name_plural': 'Зарплатный проект',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=155, verbose_name='ФИО')),
                ('category', models.CharField(choices=[('1', 'Руководитель'), ('2', 'Сотрудник'), ('3', 'Заказчик')], max_length=1, verbose_name='Категория')),
                ('account_bank', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер счета')),
                ('bank', models.CharField(blank=True, choices=[('t-bank', 'Т-банк'), ('sber', 'Сбербанк'), ('alpha', 'Альфа'), ('vtb', 'ВТБ'), ('other', 'Другое'), ('not_bank', 'Отсутствует')], default='not_bank', max_length=20, null=True, verbose_name='Банк')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.department', verbose_name='Должность')),
                ('notifications', models.ManyToManyField(blank=True, null=True, to='server.notification', verbose_name='Уведомления')),
                ('transaction', models.ManyToManyField(blank=True, null=True, to='server.transactionpayment', verbose_name='Финансовая транзакция')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователь',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование задачи')),
                ('dsc', models.TextField(verbose_name='Описание задачи')),
                ('type', models.CharField(blank=True, choices=[('backend', ' Разработка серверной логики, REST API, микросервисов.'), ('frontend', 'Интерфейсная часть, SPA, SSR.'), ('integration', 'Интеграция с внешними API, 1С, CRM, платёжками.'), ('database', 'Проектирование и оптимизация БД, миграции, индексы.'), ('devops', 'CI/CD, деплой, настройка серверов, мониторинг..'), ('ml_ai', 'Модели ИИ, аналитика, обучение, инференс.'), ('mobile', ' iOS/Android разработка.'), ('testing', 'Написание unit, e2e, нагрузочное тестирование.'), ('ux_ui', 'Проектирование пользовательского опыта, прототипы.'), ('documentation', 'Подготовка технической документации, Swagger, Confluence.'), ('architecture', 'Проектирование архитектуры решения, паттерны.'), ('security', 'Аудит безопасности, защита API, шифрование.'), ('research', 'R&D задачи, эксперименты с новыми технологиями.'), ('refactoring', 'Улучшение старого кода, устранение технического долга.'), ('support', 'Исправление багов, поддержка пользователей.')], max_length=40, null=True, verbose_name='Тип задачи')),
                ('files', models.ManyToManyField(blank=True, null=True, to='server.filetask', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='SettingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_hours', models.IntegerField(verbose_name='Плановые часы')),
                ('actual_hours', models.IntegerField(blank=True, default=0, null=True, verbose_name='Фактические часы')),
                ('scheduled_day', models.IntegerField(verbose_name='Плановые дни')),
                ('actual_day', models.IntegerField(blank=True, default=0, null=True, verbose_name='Фактические дни')),
                ('status', models.CharField(choices=[('Not_started', 'Не начата'), ('Started', 'Начата'), ('verification_staff', 'На проверке'), ('adopted', 'Принят '), ('rejected', 'Отклонен'), ('verification', 'На утверждении у заказчика'), ('adopted_customer', 'Утверждена заказчиком'), ('rejected_customer', 'Отклонено заказчиком')], default='Not_started', max_length=30, verbose_name='Статус')),
                ('is_started', models.BooleanField(default=False, verbose_name='Активна')),
                ('is_active', models.BooleanField(default=False, verbose_name='Завершена')),
                ('activity', models.ManyToManyField(blank=True, null=True, to='server.activitytask', verbose_name='Активность проекта')),
                ('feedback_customer', models.ManyToManyField(blank=True, null=True, to='server.feedbackcustomer', verbose_name='Обратная связь заказчика')),
                ('reportings', models.ManyToManyField(blank=True, null=True, to='server.reportingtask', verbose_name='Отчеты от сотрудника')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Постановка задачи',
                'verbose_name_plural': 'Постановка задач',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование раздела')),
                ('status', models.CharField(choices=[('Not_started', 'Не начат'), ('Started', 'Начат'), ('verification', 'На проверке'), ('adopted', 'Принят'), ('rejected', 'Отклонен')], default='Not_started', max_length=30, verbose_name='Статус')),
                ('reporting', models.ManyToManyField(blank=True, null=True, to='server.reportingchapter', verbose_name='Отчеты')),
                ('tasks', models.ManyToManyField(to='server.task', verbose_name='Задачи')),
            ],
            options={
                'verbose_name': 'Раздел задачи',
                'verbose_name_plural': 'Разделы задач',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Мини проект (до 3 человек)'), ('2', 'Средний проект (до 7 человек)'), ('3', 'Большой проект (до 12 человек)'), ('4', 'Крупный проект (до 18 человек)')], default='1', max_length=30, verbose_name='Тип проекта')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование проекта')),
                ('data_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('data_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('start', 'Оформление'), ('Signing_contract', 'Подписание договора'), ('Development', 'Разработка'), ('Delivery_works', 'Сдача работ'), ('Waiting', 'В ожидании'), ('Cancel', 'Отменен'), ('Completed', 'Завершен')], default='start', max_length=20, verbose_name='Статус')),
                ('payment_client', models.IntegerField(default=0, verbose_name='Оплачено клиентом')),
                ('total_cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='Итоговая стоимость')),
                ('expected_costs', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ожидаемые затраты')),
                ('actual_costs', models.IntegerField(blank=True, default=0, null=True, verbose_name='Фактические затраты')),
                ('expected_profits', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ожидаемая прибыль')),
                ('actual_profits', models.IntegerField(blank=True, default=0, null=True, verbose_name='Фактическая прибыль')),
                ('additional_costs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.additionalcosts', verbose_name='Дополнительные затраты')),
                ('chapter', models.ManyToManyField(blank=True, null=True, to='server.chapter', verbose_name='Разделы')),
                ('documents', models.ManyToManyField(blank=True, null=True, to='server.documentproject', verbose_name='Документы')),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
                ('task', models.ManyToManyField(blank=True, null=True, to='server.settingtask', verbose_name='Поставленные задачи')),
                ('transaction', models.ManyToManyField(blank=True, null=True, to='server.transactionpayment', verbose_name='Финансовая транзакция')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
